spring:
  application:
    name: firstApp
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb.firstapp.svc.cluster.local:27017/firstapp_db?authSource=admin

server:
  port: 7000
