apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstapp
  namespace: firstapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: firstapp
  template:
    metadata:
      labels:
        app: firstapp
    spec:
      containers:
        - name: firstapp
          image: firstappacr.azurecr.io/firstapp:9
          ports:
            - containerPort: 7000
      imagePullSecrets:
        - name: acr-secret